### ISSUE TITLE
stderr: fatal: unable to access 'https://github.com/coreos/coreos-ci-lib.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

### ISSUE THREAD

**Issue by cgwalters** [coreos/coreos-ci#27]
```
[2021-03-23T23:38:46.905Z] Fetching upstream changes from https://github.com/coreos/coreos-ci-lib.git
[2021-03-23T23:38:46.905Z]  > git fetch --no-tags --progress -- https://github.com/coreos/coreos-ci-lib.git +refs/heads/*:refs/remotes/origin/* # timeout=10
[2021-03-23T23:38:46.950Z] ERROR: Error fetching remote repo 'origin'
[2021-03-23T23:38:46.950Z] hudson.plugins.git.GitException: Failed to fetch from https://github.com/coreos/coreos-ci-lib.git
[2021-03-23T23:38:46.950Z] 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:909)
[2021-03-23T23:38:46.950Z] 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
[2021-03-23T23:38:46.950Z] 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
[2021-03-23T23:38:46.950Z] 	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)
[2021-03-23T23:38:46.950Z] 	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.lambda$doRetrieve$1(SCMSourceRetriever.java:154)
[2021-03-23T23:38:46.950Z] 	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrySCMOperation(SCMSourceRetriever.java:104)
[2021-03-23T23:38:46.950Z] 	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.doRetrieve(SCMSourceRetriever.java:153)
[2021-03-23T23:38:46.950Z] 	at org.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.retrieve(SCMSourceRetriever.java:93)
[2021-03-23T23:38:46.950Z] 	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.retrieve(LibraryAdder.java:157)
[2021-03-23T23:38:46.950Z] 	at org.jenkinsci.plugins.workflow.libs.LibraryAdder.add(LibraryAdder.java:138)
[2021-03-23T23:38:46.950Z] 	at org.jenkinsci.plugins.workflow.libs.LibraryDecorator$1.call(LibraryDecorator.java:125)
[2021-03-23T23:38:46.950Z] 	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
[2021-03-23T23:38:46.950Z] 	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
[2021-03-23T23:38:46.950Z] 	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
[2021-03-23T23:38:46.950Z] 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
[2021-03-23T23:38:46.950Z] 	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
[2021-03-23T23:38:46.950Z] 	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
[2021-03-23T23:38:46.951Z] 	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
[2021-03-23T23:38:46.951Z] 	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
[2021-03-23T23:38:46.951Z] 	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
[2021-03-23T23:38:46.951Z] 	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
[2021-03-23T23:38:46.951Z] 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
[2021-03-23T23:38:46.951Z] 	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
[2021-03-23T23:38:46.951Z] 	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
[2021-03-23T23:38:46.951Z] 	at hudson.model.ResourceController.execute(ResourceController.java:97)
[2021-03-23T23:38:46.951Z] 	at hudson.model.Executor.run(Executor.java:429)
[2021-03-23T23:38:46.951Z] Caused by: hudson.plugins.git.GitException: Command "git fetch --no-tags --progress -- https://github.com/coreos/coreos-ci-lib.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
[2021-03-23T23:38:46.951Z] stdout: 
[2021-03-23T23:38:46.951Z] stderr: fatal: unable to access 'https://github.com/coreos/coreos-ci-lib.git/': OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
[2021-03-23T23:38:46.951Z] 
[2021-03-23T23:38:46.951Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
[2021-03-23T23:38:46.951Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
[2021-03-23T23:38:46.951Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
[2021-03-23T23:38:46.951Z] 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
[2021-03-23T23:38:46.951Z] 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:907)
[2021-03-23T23:38:46.951Z] 	... 25 more
[2021-03-23T23:38:46.951Z] ERROR: Error fetching remote repo 'origin'
[2021-03-23T23:38:47.479Z] 
[2021-03-23T23:38:47.479Z] GitHub has been notified of this commit’s build result
[2021-03-23T23:38:47.479Z] 
[2021-03-23T23:38:47.480Z] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
[2021-03-23T23:38:47.480Z] WorkflowScript: Loading libraries failed
```

**Comment by cgwalters** [comment]
Offhand this might be rate limiting?

**Comment by jlebon** [comment]
Did you see this in multiple CI results or just the rpm-ostree one?

**Comment by cgwalters** [comment]
So far just the rpm-ostree one.

**Comment by cgwalters** [comment]
Not seeing this now so closing.
